services:
  ev-tracker:
    image: ghcr.io/an0Nym0us63/ev-tracker:latest
    container_name: ev-tracker
    ports:
      - "3080:3080"
    volumes:
      - /docker/ev-tracker-stack/data:/app/data
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped
